apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: core-app-deployment 
  template:
    metadata:
      labels:
        tier: core-app-deployment
    spec:
      containers:
        - name: core-app-deployment-container
          image: sesha1936/the-core-app
          ports :
            -containerPort:6666
---
apiVersion: v1
kind: Service
metadata:
 name: core-app-deployment
spec:
 type: ClusterIP
 ports: 
 - port: 9898
   targetPort: 6666
 selector:
  app: core-app-deployment
