apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-mvc-server
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: core-mvc--server
  template:
    metadata:
      labels:
        tier: core-mvc-server
    spec:
      containers:
      - name: core-mvc--server-container
        image: sesha1936/the-core-app
        ports :
        - containerPort: 6666